Algoritmo "Problema soma"
// Disciplina   : Matemática Itinerário - Módulo de Programação
// Professor   : Igo Anderson Santos Oliveira 
// Autor(a)    : Karla Beatriz Costa Silva
// Data atual  : 28/05/2025
Var
x:inteiro
y:inteiro
soma:inteiro
Inicio
escreva("Declare um valor inteiro para x:")
leia(x)
escreva("Declare um valor inteiro para y:")
leia(y)
soma<-(x+y)
escreval("A soma desses valores é de: ",soma,".")
Fimalgoritmo